lsi: false
safe: true
source: ''
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: XPlus Games Docs
description: Documentation for Xplus Games' Projects
